# Generated by Django 5.0.6 on 2024-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="model_Hanja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=1)),
                ("form", models.CharField(max_length=2)),
                ("explanation", models.CharField(max_length=100)),
                ("component_core", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="model_Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
