# Generated by Django 5.0.6 on 2024-07-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_0", "0002_model_person_endowment_model_person_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="model_hanja",
            name="component_combined",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="model_hanja",
            name="component_meaning",
            field=models.CharField(default="一", max_length=5),
        ),
        migrations.AddField(
            model_name="model_hanja",
            name="component_sound",
            field=models.CharField(default="一", max_length=5),
        ),
        migrations.AddField(
            model_name="model_hanja",
            name="is_component",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="model_hanja",
            name="lev_read",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="model_hanja",
            name="lev_write",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="model_hanja",
            name="meaning",
            field=models.CharField(default="一", max_length=30),
        ),
        migrations.AddField(
            model_name="model_hanja",
            name="meaning_sound",
            field=models.CharField(default="하나 일", max_length=30),
        ),
        migrations.AddField(
            model_name="model_hanja",
            name="sound",
            field=models.CharField(default="일", max_length=10),
        ),
        migrations.AddField(
            model_name="model_hanja",
            name="trace",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="component_core",
            field=models.CharField(default="一", max_length=1),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="explanation",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="form",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="word",
            field=models.CharField(default="一", max_length=1),
        ),
    ]
