# Generated by Django 5.0.6 on 2024-07-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_0", "0004_remove_model_hanja_component_combined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="model_hanja",
            name="origin",
            field=models.CharField(default="一", max_length=1),
        ),
    ]
