# Generated by Django 5.0.6 on 2024-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_0", "0007_alter_model_hanja_meaning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model_hanja",
            name="meaning_sound",
            field=models.CharField(default="하나 일", max_length=50),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="sound",
            field=models.CharField(default="일", max_length=30),
        ),
    ]
