# Generated by Django 5.0.6 on 2024-07-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_0", "0009_alter_model_hanja_component_sound"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model_hanja",
            name="component_sound",
            field=models.CharField(
                db_collation="utf8mb4_unicode_ci", default="一", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="origin",
            field=models.CharField(
                db_collation="utf8mb4_unicode_ci", default="一", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="trace",
            field=models.CharField(
                db_collation="utf8mb4_unicode_ci", default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="word",
            field=models.CharField(
                db_collation="utf8mb4_unicode_ci", default="一", max_length=1
            ),
        ),
    ]
