# Generated by Django 5.0.6 on 2024-07-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_0", "0010_alter_model_hanja_component_sound_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model_person",
            name="endowment",
        ),
        migrations.AddField(
            model_name="model_person",
            name="hanjas",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="model_person",
            name="know_component",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="model_person",
            name="know_hanja",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="model_person",
            name="result",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="model_person",
            name="time",
            field=models.FloatField(default=0),
        ),
    ]
