# Generated by Django 5.0.6 on 2024-07-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_0", "0011_remove_model_person_endowment_model_person_hanjas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model_person",
            name="phone",
            field=models.TextField(default=""),
        ),
    ]
