# Generated by Django 5.0.7 on 2024-07-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0013_model_person_sampling_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_person',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
