# Generated by Django 5.0.6 on 2024-07-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_0", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model_person",
            name="endowment",
            field=models.CharField(default="noname", max_length=10),
        ),
        migrations.AddField(
            model_name="model_person",
            name="phone",
            field=models.IntegerField(default=0),
        ),
    ]
