# Generated by Django 5.0.6 on 2024-07-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_0", "0003_model_hanja_component_combined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model_hanja",
            name="component_combined",
        ),
        migrations.RemoveField(
            model_name="model_hanja",
            name="component_core",
        ),
        migrations.RemoveField(
            model_name="model_hanja",
            name="is_component",
        ),
        migrations.AddField(
            model_name="model_hanja",
            name="one_stroke",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="model_hanja",
            name="total_stroke",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="component_meaning",
            field=models.CharField(default="一", max_length=1),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="component_sound",
            field=models.CharField(default="一", max_length=1),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="form",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="model_hanja",
            name="trace",
            field=models.CharField(default="", max_length=10),
        ),
    ]
