# Generated by Django 5.0.6 on 2024-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_0", "0012_alter_model_person_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="model_person",
            name="sampling_type",
            field=models.IntegerField(default=-1),
        ),
    ]
